// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ifqlbimpizepdagizkcq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlmcWxiaW1waXplcGRhZ2l6a2NxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0ODQ0MTgsImV4cCI6MjA3MDA2MDQxOH0.OShVdtcc81ARVUWjTHyVSlKMvqW4D49w40RLkLy0V1w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});